# See https://github.com/sturdy-dev/codeball-action for more information of how to use this action
name: Codeball AI Code Review
description: AI Code Review – Codeball approves Pull Requests that a human would have approved. Wait less for review, save time and money.

author: Sturdy
branding:
  icon: check
  color: orange

runs:
  using: 'composite'
  steps:

    # Start a new Codeball review job
    # This step is asynchronous and will return a job id
    - name: Trigger Codeball
      id: codeball_baller
      uses: sturdy-dev/codeball-action/baller@v2

    # Wait for Codeball to return the status
    - name: Get Status
      id: codeball_status
      uses: sturdy-dev/codeball-action/status@v2
      with:
        codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}

    # If Codeball approved the contribution, add a "codeball:approved" label
    - name: Label Approved
      uses: sturdy-dev/codeball-action/labeler@v2
      if: ${{ steps.codeball_status.outputs.approved == 'true' }}
      with:
        name: "codeball:approved"
        color: "86efac" # green
        codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}

    # If Codeball approved the contribution, approve the PR
    - name: Approve PR
      uses: sturdy-dev/codeball-action/approver@v2
      if: ${{ steps.codeball_status.outputs.approved == 'true' }}
      with:
        codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}
