# See https://github.com/sturdy-dev/codeball-action for more information of how to use this aciont
name: Codeball AI Actions
description: AI Code Review

author: Sturdy
branding:
  icon: check
  color: orange

runs:
  using: "composite"
  steps:
    # Start a new Codeball review job
    # This step is asynchronous and will return a job id
    - name: Trigger Codeball
      id: codeball_baller
      uses: sturdy-dev/codeball-action/baller@main

    # Wait for the codeball_baller job to complete
    # Approves the Pull Request if Codeball approves it
    - name: Codeball Approver
      id: codeball_approver
      uses: sturdy-dev/codeball-action/approver@main
      with:
        codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}
