# See https://github.com/sturdy-dev/codeball-action for more information of how to use this action
name: Codeball AI Actions
description: AI Code Review

author: Sturdy
branding:
  icon: check
  color: orange

inputs:
  do-label:
    description: 'If true, Codeball will label Pull Request.'
    default: true
    required: false
  label-value:
    description: 'Label value to be set.'
    default: 'codeball:approved'
    required: false
  do-approve:
    description: 'If true, Codeball will approve Pull Request.'
    default: true
    required: false

runs:
  using: 'composite'
  steps:
    # Start a new Codeball review job
    # This step is asynchronous and will return a job id
    - name: Trigger Codeball
      id: codeball_baller
      uses: ngalaiko/codeball-action/baller@main

    # Wait for the codeball_baller job to complete
    # Approves the Pull Request if Codeball approves it
    - name: Codeball Approver
      id: codeball_approver
      uses: ngalaiko/codeball-action/approver@main
      with:
        codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}
        do-label: ${{ inputs.do-label }}
        label-value: ${{ inputs.label-value }}
        do-approve: ${{ inputs.do-approve }}
