name: 'Codeball Approver'
description: 'Codeball Approver (beta)'

branding:
  icon: check
  color: orange

inputs:
  GITHUB_TOKEN:
    description: 'Default to {{ github.token }}. This is the default GitHub token available to actions and is used to run Codeball and to post the result. The default token permissions (https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) work fine.'
    default: '${{ github.token }}'
    required: false
  message:
    description: 'The message to send in the code review comment.'
    default: "Codeball: LGTM! :+1:"
    required: false
  codeball-job-id:
    description: 'The ID of the Codeball Job created by the Baller Action'
    required: false
  approve:
    description: "If set to 'true', will approve pull request"
    default: true
    required: true

runs:
  using: 'node16'
  main: '../dist/approver/index.js'
