name: 'Codeball Labeler'
description: 'Codeball Labeler (beta)'

branding:
  icon: check
  color: orange

inputs:
  GITHUB_TOKEN:
    description: 'Default to {{ github.token }}. This is the default GitHub token available to actions and is used to run Codeball and to post the result. The default token permissions (https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) work fine.'
    default: '${{ github.token }}'
    required: false
  name:
    description: "The name of the label. Will be created if it does not exist."
    required: true
  color:
    description: "The color of the label."
    default: "008E43"
    required: false
  description:
    description: "The description of the label."
    default: "Codeball"
    required: false

runs:
  using: 'node16'
  main: '../dist/labeler/index.js'
