name: 'Codeball Status'
description: 'Codeball Status (beta)'

branding:
  icon: check
  color: orange

inputs:
  codeball-job-id:
    description: 'The ID of the Codeball Job created by the Baller Action'
    required: true

outputs:
  jobType:
    description: 'The type of Codeball job ("contribution" or "comment")'
  approved:
    description: 'If the Codeball approved the contribution (true or false)'
  suggested:
    description: 'If the Codeball has suggestions for the contribution (true or false)'
  confidence:
    description: 'The Codeball confidence that this contribution can be approved as-is. A number between 0 and 1. A value between 0 and 0.3 normally indicates that the contribution should be thoroughly reviewed. A value above 0.93 indicates that the contribution is very likely to be approved as-is. Confidence is only set for contribution jobs.'

runs:
  using: 'node16'
  main: '../dist/status/index.js'
