on: [pull_request]
name: Codeball
jobs:
  codeball_job:
    if: github.repository == 'sturdy-dev/codeball-action'
    runs-on: ubuntu-latest
    name: Codeball
    steps:
    
    # Start a new Codeball review job
    # This step is asynchronous and will return a job id
    - name: Trigger Codeball
      id: codeball_baller
      uses: sturdy-dev/codeball-action/baller@v2

    # Wait for Codeball to return the status
    - name: Get Status
      id: codeball_status
      uses: sturdy-dev/codeball-action/status@v2
      with:
        codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}

    # If Codeball approved the contribution, add a "codeball:approved" label
    - name: Label Approved
      uses: sturdy-dev/codeball-action/labeler@v2
      if: ${{ steps.codeball_status.outputs.approved == 'true' }}
      with:
        name: "codeball:approved"
        color: "86efac" # green

    # If Codeball did not approve the contribution, add a "codeball:needs-review" label
    - name: Label Approved
      uses: sturdy-dev/codeball-action/labeler@v2
      if: ${{ steps.codeball_status.outputs.approved == 'false' }}
      with:
        name: "codeball:needs-review"
        color: "bfdbfe" # blue

    # If Codeball approved the contribution, approve the PR
    - name: Approve PR
      uses: sturdy-dev/codeball-action/approver@v2
      if: ${{ steps.codeball_status.outputs.approved == 'true' }}
